# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Stem French words
#'
#' Stemmer for French words
#'
#' @param words a [character] containing the original words.
#' @return [character] with stemmed words.
#' @examples
#' french_stemmer(c("tester", "testament", "clients"))
#' @export
french_stemmer <- function(words) {
    .Call(`_unine_french_stemmer`, words)
}

